/** 命令 ID 常量表，供注册表与调用方统一引用。 */
export const COMMAND_ID = {
  APP_OPEN_COMMAND_PALETTE: "app.openCommandPalette",
  APP_TOGGLE_PROBLEMS_PANEL: "app.toggleProblemsPanel",
  FILE_NEW_DOCUMENT: "file.newDocument",
  FILE_OPEN_IMAGE: "file.openImage",
  FILE_SAVE: "file.save",
  FILE_SAVE_ALL: "file.saveAll",
  FILE_RENAME: "file.rename",
  FILE_REPLACE_IMAGE: "file.replaceImage",
  FILE_REVEAL_IN_EXPLORER: "file.revealInExplorer",
  FILE_CLOSE_ACTIVE: "file.closeActive",
  FILE_CLOSE_ALL: "file.closeAll",
  EDIT_UNDO: "edit.undo",
  EDIT_REDO: "edit.redo",
  DEFINITION_DUPLICATE_SELECTED: "definition.duplicateSelected",
  DEFINITION_COPY_SELECTED: "definition.copySelected",
  DEFINITION_CUT_SELECTED: "definition.cutSelected",
  DEFINITION_DELETE_SELECTED: "definition.deleteSelected",
  DEFINITION_PASTE_FROM_CLIPBOARD: "definition.pasteFromClipboard",
  VARIANT_NEW_DOCUMENT: "variant.newDocument",
  VARIANT_NEW_FROM_CLIPBOARD: "variant.newFromClipboard",
  VARIANT_NEW_FROM_DEVICE: "variant.newFromDevice",
  VARIANT_COPY_SELECTED_PREFAB: "variant.copySelectedPrefab",
  VARIANT_RENAME_VARIANTS_FOR_DEFINITION: "variant.renameVariantsForDefinition",
  SYMBOL_RENAME_FOR_DEFINITION: "symbol.renameForDefinition",
  APP_OPEN_PREFERENCES: "app.openPreferences",
  DOCUMENT_CLOSE: "document.close",
  DOCUMENT_CLOSE_MANY: "document.closeMany",
  NAVIGATION_JUMP_TO_SYMBOL: "navigation.jumpToSymbol",
  NAVIGATION_JUMP_TO_DIAGNOSTIC: "navigation.jumpToDiagnostic",
} as const;
