/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/fs/list_dir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dir */
        get: operations["list_dir_api_fs_list_dir_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/read_text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Text */
        get: operations["read_text_api_fs_read_text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/write_text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Write Text */
        put: operations["write_text_api_fs_write_text_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rename Path */
        post: operations["rename_path_api_fs_rename_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/copy_file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy File */
        post: operations["copy_file_api_fs_copy_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/upload_file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload File */
        post: operations["upload_file_api_fs_upload_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/reveal_in_explorer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal In Explorer */
        post: operations["reveal_in_explorer_api_fs_reveal_in_explorer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/folder_tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Folder Tree */
        get: operations["get_folder_tree_api_fs_folder_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/root": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Root */
        get: operations["get_project_root_api_project_root_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/list_images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspace Images */
        get: operations["list_workspace_images_api_project_list_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/symbol_tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Symbol Tree */
        get: operations["get_project_symbol_tree_api_project_symbol_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image */
        get: operations["get_image_api_image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Thumbnail */
        get: operations["get_image_thumbnail_api_image_thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image/hover_preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Hover Preview */
        get: operations["get_image_hover_preview_api_image_hover_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prefabs/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prefabs Schema */
        get: operations["get_prefabs_schema_api_prefabs_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta Index */
        get: operations["get_meta_index_api_meta_index_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/index/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Meta Index */
        post: operations["update_meta_index_api_meta_index_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta Diagnostics */
        get: operations["get_meta_diagnostics_api_meta_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/index/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta Index Health */
        get: operations["get_meta_index_health_api_meta_index_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/variant/clone_to_image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone Variant To Image */
        post: operations["clone_variant_to_image_api_meta_variant_clone_to_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/variant/import/precheck_path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Precheck Variant Import Path */
        post: operations["precheck_variant_import_path_api_meta_variant_import_precheck_path_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/variant/import_image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Variant Image */
        post: operations["import_variant_image_api_meta_variant_import_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/variant/copy_selected_prefab/precheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Precheck Copy Selected Prefab To Variant */
        post: operations["precheck_copy_selected_prefab_to_variant_api_meta_variant_copy_selected_prefab_precheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/variant/copy_selected_prefab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy Selected Prefab To Variant */
        post: operations["copy_selected_prefab_to_variant_api_meta_variant_copy_selected_prefab_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/rename_document/precheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Precheck Rename Document */
        post: operations["precheck_rename_document_api_fs_rename_document_precheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/rename_document/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Rename Document */
        post: operations["execute_rename_document_api_fs_rename_document_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/document/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Document */
        post: operations["create_document_api_document_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/suggest_path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggest Document Path */
        post: operations["suggest_document_path_api_ai_suggest_path_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/infer_definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Infer Definitions */
        post: operations["infer_definitions_api_ai_infer_definitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/device/adb/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Adb Devices */
        get: operations["list_adb_devices_api_device_adb_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/device/adb/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capture Adb Screenshot */
        get: operations["capture_adb_screenshot_api_device_adb_screenshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversion/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Conversion Execute */
        post: operations["conversion_execute_api_conversion_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversion/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Conversion Scan */
        post: operations["conversion_scan_api_conversion_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversion/scan_progress/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conversion Scan Progress */
        get: operations["conversion_scan_progress_api_conversion_scan_progress__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversion/scan/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Conversion Cancel Scan */
        delete: operations["conversion_cancel_scan_api_conversion_scan__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Server Commands */
        get: operations["get_server_commands_api_server_commands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/execute_command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Server Command */
        post: operations["execute_server_command_api_server_execute_command_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spa Catchall */
        get: operations["spa_catchall___path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_document_api_document_create_post */
        Body_create_document_api_document_create_post: {
            /** Targetpath */
            targetPath: string;
            /**
             * Image
             * Format: binary
             */
            image: string;
        };
        /** Body_import_variant_image_api_meta_variant_import_image_post */
        Body_import_variant_image_api_meta_variant_import_image_post: {
            /** Baseimagepath */
            baseImagePath: string;
            /** Variant */
            variant: string;
            /**
             * Image
             * Format: binary
             */
            image: string;
            /**
             * Deleteexistingtarget
             * @default false
             */
            deleteExistingTarget: boolean;
        };
        /** Body_infer_definitions_api_ai_infer_definitions_post */
        Body_infer_definitions_api_ai_infer_definitions_post: {
            /**
             * Image
             * Format: binary
             */
            image: string;
            /** Definitionsjson */
            definitionsJson: string;
            /** Imagepath */
            imagePath: string;
            /** Providertype */
            providerType: string;
            /**
             * Endpoint
             * @default
             */
            endpoint: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Apikey
             * @default
             */
            apiKey: string;
        };
        /** Body_precheck_variant_import_path_api_meta_variant_import_precheck_path_post */
        Body_precheck_variant_import_path_api_meta_variant_import_precheck_path_post: {
            /** Sourcemetapath */
            sourceMetaPath: string;
            /** Baseimagepath */
            baseImagePath: string;
            /** Variant */
            variant: string;
            /**
             * Image
             * Format: binary
             */
            image: string;
        };
        /** Body_suggest_document_path_api_ai_suggest_path_post */
        Body_suggest_document_path_api_ai_suggest_path_post: {
            /**
             * Image
             * Format: binary
             */
            image: string;
            /** Providertype */
            providerType: string;
            /**
             * Endpoint
             * @default
             */
            endpoint: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Apikey
             * @default
             */
            apiKey: string;
        };
        /** Body_upload_file_api_fs_upload_file_post */
        Body_upload_file_api_fs_upload_file_post: {
            /** Targetpath */
            targetPath: string;
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * CaptureScreenshotResponse
         * @description 设备截图响应。
         *
         *     成功时填充 ``imagePath`` 与 ``imageUrl``，失败时仅填充 ``success=False`` 与 ``error``。
         */
        CaptureScreenshotResponse: {
            /** Success */
            success: boolean;
            /** Imagepath */
            imagePath?: string | null;
            /** Imageurl */
            imageUrl?: string | null;
            /** Error */
            error?: string | null;
        };
        /** CloneVariantToImageRequest */
        CloneVariantToImageRequest: {
            /** Sourcemetapath */
            sourceMetaPath: string;
            /** Targetimagepath */
            targetImagePath: string;
            /** Variant */
            variant: string;
            /**
             * Forceoverwrite
             * @default false
             */
            forceOverwrite: boolean;
        };
        /**
         * ConfirmedMatch
         * @description 用户确认后的单条转换项。
         */
        ConfirmedMatch: {
            /** Singlemetapath */
            singleMetaPath: string | null;
            /** Singleimagepath */
            singleImagePath: string;
            /** Matchedimagepath */
            matchedImagePath: string;
            /** Matchx */
            matchX: number;
            /** Matchy */
            matchY: number;
            /** Matchw */
            matchW: number;
            /** Matchh */
            matchH: number;
            /** Targetmetapath */
            targetMetaPath?: string | null;
        };
        /**
         * ConversionExecuteResponse
         * @description 转换执行结果。
         */
        ConversionExecuteResponse: {
            /** Modifiedmetapaths */
            modifiedMetaPaths: string[];
            /** Deletedsinglemetapaths */
            deletedSingleMetaPaths: string[];
            /** Deletedsingleimagepaths */
            deletedSingleImagePaths: string[];
        };
        /**
         * ConversionMatch
         * @description 单个匹配结果：single 文档模板在目标图片中的命中记录。
         */
        ConversionMatch: {
            /** Singlemetapath */
            singleMetaPath: string | null;
            /** Singleimagepath */
            singleImagePath: string;
            /** Matchedimagepath */
            matchedImagePath: string;
            /** Matchscore */
            matchScore: number;
            /** Matchx */
            matchX: number;
            /** Matchy */
            matchY: number;
            /** Matchw */
            matchW: number;
            /** Matchh */
            matchH: number;
        };
        /**
         * CopyFileRequest
         * @description 文件拷贝覆盖请求。
         */
        CopyFileRequest: {
            /** Sourcepath */
            sourcePath: string;
            /** Targetpath */
            targetPath: string;
        };
        /**
         * CopyPrefabPrecheckResult
         * @description 复制 Prefab 预检结果。
         */
        CopyPrefabPrecheckResult: {
            /** Targetimagepath */
            targetImagePath: string;
            /** Targetimageexists */
            targetImageExists: boolean;
            /** Targetmetapath */
            targetMetaPath: string;
            /** Targetmetaexists */
            targetMetaExists: boolean;
            /** Targetdefinitionexists */
            targetDefinitionExists: boolean;
            /** Sourcedefinitionid */
            sourceDefinitionId: string;
            /** Sourcedefinitionname */
            sourceDefinitionName: string;
            /** Targetdefinition */
            targetDefinition: {
                [key: string]: unknown;
            };
            /** Targetdefinitionoverwritten */
            targetDefinitionOverwritten?: boolean | null;
        };
        /**
         * CopyPrefabResult
         * @description 复制 Prefab 结果。
         */
        CopyPrefabResult: {
            /** Targetimagepath */
            targetImagePath: string;
            /** Targetmetapath */
            targetMetaPath: string;
            /** Definitionid */
            definitionId: string;
            /** Definitionname */
            definitionName: string;
            /** Targetdefinitionoverwritten */
            targetDefinitionOverwritten: boolean;
        };
        /**
         * CopyResult
         * @description 拷贝结果。
         */
        CopyResult: {
            /** Status */
            status: string;
            /** Target Path */
            target_path: string;
        };
        /** CopySelectedPrefabToVariantRequest */
        CopySelectedPrefabToVariantRequest: {
            /** Sourcemetapath */
            sourceMetaPath: string;
            /** Sourcedefinitionid */
            sourceDefinitionId: string;
            /** Baseimagepath */
            baseImagePath: string;
            /** Variant */
            variant: string;
            /**
             * Forceoverwrite
             * @default false
             */
            forceOverwrite: boolean;
        };
        /**
         * CreateDocumentResult
         * @description 创建文档结果。
         */
        CreateDocumentResult: {
            /** Imagepath */
            imagePath: string;
            /** Metapath */
            metaPath: string;
        };
        /**
         * DeviceInfo
         * @description ADB 设备信息。
         */
        DeviceInfo: {
            /** Serial */
            serial: string;
            /** State */
            state: string;
            /** Name */
            name: string;
        };
        /**
         * DeviceListResult
         * @description ADB 设备列表结果。
         */
        DeviceListResult: {
            /** Devices */
            devices: components["schemas"]["DeviceInfo"][];
            /** Error */
            error?: string | null;
        };
        /** DiagnosticPayloadModel */
        DiagnosticPayloadModel: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Meta Path */
            meta_path: string;
            /** Severity */
            severity: string;
            /** Definition Id */
            definition_id: string | null;
            /** Field Path */
            field_path: string | null;
            /** Line */
            line: number;
            /** Column */
            column: number;
            /** Endline */
            endLine: number;
            /** Endcolumn */
            endColumn: number;
        };
        /** EditorData */
        EditorData: {
            /** Prefabs Module */
            prefabs_module?: string | null;
            /** Resource Path */
            resource_path?: string | null;
            /** R File */
            r_file?: string | null;
        };
        /** ExecuteConversionRequest */
        ExecuteConversionRequest: {
            /** Matches */
            matches: components["schemas"]["ConfirmedMatch"][];
        };
        /**
         * ExecuteRenameDocumentRequest
         * @description 文档重命名执行请求。
         */
        ExecuteRenameDocumentRequest: {
            /** Sourceimagepath */
            sourceImagePath: string;
            /** Targetimagepath */
            targetImagePath: string;
        };
        /**
         * FolderTreeNode
         * @description 目录树节点。
         */
        FolderTreeNode: {
            /** Name */
            name: string;
            /** Children */
            children: components["schemas"]["FolderTreeNode"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResult
         * @description 健康检查结果。
         */
        HealthResult: {
            /** Status */
            status: string;
            /** Service */
            service: string;
        };
        /**
         * InferDefinitionsResult
         * @description AI 定义推断结果。
         */
        InferDefinitionsResult: {
            /** Definitions */
            definitions: {
                [key: string]: unknown;
            };
        };
        /**
         * ListDirItem
         * @description 目录条目（HTTP 响应）。
         *
         *     ``thumbnailUrl`` 仅在条目为图片时由路由填充，否则为 None。
         */
        ListDirItem: {
            /** Name */
            name: string;
            /** Isdirectory */
            isDirectory: boolean;
            /** Path */
            path: string;
            /** Isimage */
            isImage: boolean;
            /** Thumbnailurl */
            thumbnailUrl?: string | null;
        };
        /**
         * ListDirResponse
         * @description 列出目录响应。
         */
        ListDirResponse: {
            /** Items */
            items: components["schemas"]["ListDirItem"][];
        };
        /**
         * ListImagesResponse
         * @description 工作区图片列表响应。
         */
        ListImagesResponse: {
            /** Imagepaths */
            imagePaths: string[];
        };
        /**
         * MetaDiagnosticsSnapshotModel
         * @description 诊断快照。
         */
        MetaDiagnosticsSnapshotModel: {
            /** Indexversion */
            indexVersion: number;
            /** Diagnosticsbyfile */
            diagnosticsByFile: {
                [key: string]: components["schemas"]["DiagnosticPayloadModel"][];
            };
            stats: components["schemas"]["MetaDiagnosticsStatsModel"];
        };
        /**
         * MetaDiagnosticsStatsModel
         * @description 诊断统计。
         */
        MetaDiagnosticsStatsModel: {
            /** Total */
            total: number;
            /** Error */
            error: number;
            /** Warning */
            warning: number;
            /** Info */
            info: number;
        };
        /** MetaRefetchResult */
        MetaRefetchResult: {
            index: components["schemas"]["SymbolSnapshotLiteModel"];
            diagnostics: components["schemas"]["MetaDiagnosticsSnapshotModel"];
        };
        /** PrecheckCopySelectedPrefabToVariantRequest */
        PrecheckCopySelectedPrefabToVariantRequest: {
            /** Sourcemetapath */
            sourceMetaPath: string;
            /** Sourcedefinitionid */
            sourceDefinitionId: string;
            /** Baseimagepath */
            baseImagePath: string;
            /** Variant */
            variant: string;
        };
        /**
         * PrecheckRenameDocumentRequest
         * @description 文档重命名预检请求。
         */
        PrecheckRenameDocumentRequest: {
            /** Sourceimagepath */
            sourceImagePath: string;
            /** Targetimagepath */
            targetImagePath: string;
        };
        /**
         * PrefabsSchema
         * @description Prefab 模式版本。
         */
        PrefabsSchema: {
            /** Version */
            version: number;
            /** Prefabs */
            prefabs: {
                [key: string]: unknown;
            };
        };
        /**
         * ProjectRootData
         * @description 项目根数据。
         */
        ProjectRootData: {
            /** Resource Root */
            resource_root: string;
            editor?: components["schemas"]["EditorData"] | null;
            variant?: components["schemas"]["VariantData"] | null;
        };
        /**
         * ReadTextResponse
         * @description 读取文本响应。
         */
        ReadTextResponse: {
            /** Content */
            content: string;
        };
        /**
         * RenameDocumentExecuteResultModel
         * @description 文档重命名执行结果。
         */
        RenameDocumentExecuteResultModel: {
            /** Documents */
            documents: components["schemas"]["RenameDocumentItemModel"][];
            /** Filerenames */
            fileRenames: components["schemas"]["RenameFileItemModel"][];
            /** Renamedfilecount */
            renamedFileCount: number;
            /** Renameddocumentcount */
            renamedDocumentCount: number;
        };
        /**
         * RenameDocumentItemModel
         * @description 文档重命名单项。
         */
        RenameDocumentItemModel: {
            /** Variant */
            variant: string;
            /** Sourceimagepath */
            sourceImagePath: string;
            /** Targetimagepath */
            targetImagePath: string;
            /** Sourcemetapath */
            sourceMetaPath: string;
            /** Targetmetapath */
            targetMetaPath: string;
        };
        /**
         * RenameDocumentPrecheckResultModel
         * @description 文档重命名预检结果。
         */
        RenameDocumentPrecheckResultModel: {
            /** Documents */
            documents: components["schemas"]["RenameDocumentItemModel"][];
            /** Filerenames */
            fileRenames: components["schemas"]["RenameFileItemModel"][];
            /** Conflicts */
            conflicts: string[];
            /** Hasconflicts */
            hasConflicts: boolean;
        };
        /**
         * RenameFileItemModel
         * @description 文件重命名单项。
         */
        RenameFileItemModel: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "image" | "meta";
            /** Variant */
            variant: string;
            /** Sourcepath */
            sourcePath: string;
            /** Targetpath */
            targetPath: string;
        };
        /**
         * RenamePathRequest
         * @description 单文件重命名请求。
         */
        RenamePathRequest: {
            /** Sourcepath */
            sourcePath: string;
            /** Targetpath */
            targetPath: string;
        };
        /**
         * RenameResult
         * @description 重命名结果。
         */
        RenameResult: {
            /** Source Path */
            source_path: string;
            /** Target Path */
            target_path: string;
        };
        /** RenameSymbolExecuteResult */
        RenameSymbolExecuteResult: {
            /** Sourcemetapath */
            sourceMetaPath: string;
            /** Sourcedefinitionid */
            sourceDefinitionId: string;
            /** Oldname */
            oldName: string;
            /** Newname */
            newName: string;
            /** Targets */
            targets: components["schemas"]["RenameSymbolTargetModel"][];
            /** Affectedmetacount */
            affectedMetaCount: number;
            /** Affecteddefinitioncount */
            affectedDefinitionCount: number;
            /** Updatedindexversion */
            updatedIndexVersion: number;
            /** Updatedcontenthash */
            updatedContentHash: string;
        };
        /** RenameSymbolPrecheckResult */
        RenameSymbolPrecheckResult: {
            /** Sourcemetapath */
            sourceMetaPath: string;
            /** Sourcedefinitionid */
            sourceDefinitionId: string;
            /** Oldname */
            oldName: string;
            /** Newname */
            newName: string;
            /** Targets */
            targets: components["schemas"]["RenameSymbolTargetModel"][];
            /** Affectedmetacount */
            affectedMetaCount: number;
            /** Affecteddefinitioncount */
            affectedDefinitionCount: number;
        };
        /** RenameSymbolTargetModel */
        RenameSymbolTargetModel: {
            /** Symbolkey */
            symbolKey: string;
            /** Metapath */
            metaPath: string;
            /** Imagepath */
            imagePath: string;
            /** Definitionid */
            definitionId: string;
            /** Variant */
            variant: string | null;
            /** Type */
            type: string;
            /** Oldname */
            oldName: string;
            /** Newname */
            newName: string;
        };
        /** ResponseModel[CaptureScreenshotResponse] */
        ResponseModel_CaptureScreenshotResponse_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["CaptureScreenshotResponse"] | null;
        };
        /** ResponseModel[ConversionExecuteResponse] */
        ResponseModel_ConversionExecuteResponse_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["ConversionExecuteResponse"] | null;
        };
        /** ResponseModel[CopyPrefabPrecheckResult] */
        ResponseModel_CopyPrefabPrecheckResult_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["CopyPrefabPrecheckResult"] | null;
        };
        /** ResponseModel[CopyPrefabResult] */
        ResponseModel_CopyPrefabResult_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["CopyPrefabResult"] | null;
        };
        /** ResponseModel[CopyResult] */
        ResponseModel_CopyResult_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["CopyResult"] | null;
        };
        /** ResponseModel[CreateDocumentResult] */
        ResponseModel_CreateDocumentResult_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["CreateDocumentResult"] | null;
        };
        /** ResponseModel[DeviceListResult] */
        ResponseModel_DeviceListResult_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["DeviceListResult"] | null;
        };
        /** ResponseModel[HealthResult] */
        ResponseModel_HealthResult_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["HealthResult"] | null;
        };
        /** ResponseModel[InferDefinitionsResult] */
        ResponseModel_InferDefinitionsResult_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["InferDefinitionsResult"] | null;
        };
        /** ResponseModel[ListDirResponse] */
        ResponseModel_ListDirResponse_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["ListDirResponse"] | null;
        };
        /** ResponseModel[ListImagesResponse] */
        ResponseModel_ListImagesResponse_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["ListImagesResponse"] | null;
        };
        /** ResponseModel[MetaDiagnosticsSnapshotModel] */
        ResponseModel_MetaDiagnosticsSnapshotModel_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["MetaDiagnosticsSnapshotModel"] | null;
        };
        /** ResponseModel[NoneType] */
        ResponseModel_NoneType_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Data */
            data?: null;
        };
        /** ResponseModel[PrefabsSchema] */
        ResponseModel_PrefabsSchema_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["PrefabsSchema"] | null;
        };
        /** ResponseModel[ProjectRootData] */
        ResponseModel_ProjectRootData_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["ProjectRootData"] | null;
        };
        /** ResponseModel[ReadTextResponse] */
        ResponseModel_ReadTextResponse_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["ReadTextResponse"] | null;
        };
        /** ResponseModel[RenameDocumentExecuteResultModel] */
        ResponseModel_RenameDocumentExecuteResultModel_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["RenameDocumentExecuteResultModel"] | null;
        };
        /** ResponseModel[RenameDocumentPrecheckResultModel] */
        ResponseModel_RenameDocumentPrecheckResultModel_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["RenameDocumentPrecheckResultModel"] | null;
        };
        /** ResponseModel[RenameResult] */
        ResponseModel_RenameResult_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["RenameResult"] | null;
        };
        /** ResponseModel[ScanProgress] */
        ResponseModel_ScanProgress_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["ScanProgress"] | null;
        };
        /** ResponseModel[ScanStartResponse] */
        ResponseModel_ScanStartResponse_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["ScanStartResponse"] | null;
        };
        /** ResponseModel[SuggestPathResponse] */
        ResponseModel_SuggestPathResponse_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["SuggestPathResponse"] | null;
        };
        /** ResponseModel[SymbolIndexHealthModel] */
        ResponseModel_SymbolIndexHealthModel_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["SymbolIndexHealthModel"] | null;
        };
        /** ResponseModel[SymbolSnapshotLiteModel] */
        ResponseModel_SymbolSnapshotLiteModel_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["SymbolSnapshotLiteModel"] | null;
        };
        /** ResponseModel[SymbolUpdateResultModel] */
        ResponseModel_SymbolUpdateResultModel_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["SymbolUpdateResultModel"] | null;
        };
        /** ResponseModel[Union[MetaRefetchResult, SymbolUpdateResultModel, RenameDocumentPrecheckResultModel, RenameDocumentExecuteResultModel, RenameSymbolPrecheckResult, RenameSymbolExecuteResult, VariantCloneToImageResult, VariantImportImageResult, VariantCopySelectedPrefabPrecheckResult]] */
        ResponseModel_Union_MetaRefetchResult__SymbolUpdateResultModel__RenameDocumentPrecheckResultModel__RenameDocumentExecuteResultModel__RenameSymbolPrecheckResult__RenameSymbolExecuteResult__VariantCloneToImageResult__VariantImportImageResult__VariantCopySelectedPrefabPrecheckResult__: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Data */
            data?: components["schemas"]["MetaRefetchResult"] | components["schemas"]["SymbolUpdateResultModel"] | components["schemas"]["RenameDocumentPrecheckResultModel"] | components["schemas"]["RenameDocumentExecuteResultModel"] | components["schemas"]["RenameSymbolPrecheckResult"] | components["schemas"]["RenameSymbolExecuteResult"] | components["schemas"]["VariantCloneToImageResult"] | components["schemas"]["VariantImportImageResult"] | components["schemas"]["VariantCopySelectedPrefabPrecheckResult"] | null;
        };
        /** ResponseModel[UploadResult] */
        ResponseModel_UploadResult_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["UploadResult"] | null;
        };
        /** ResponseModel[VariantCloneResult] */
        ResponseModel_VariantCloneResult_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["VariantCloneResult"] | null;
        };
        /** ResponseModel[VariantImportPrecheckResult] */
        ResponseModel_VariantImportPrecheckResult_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["VariantImportPrecheckResult"] | null;
        };
        /** ResponseModel[VariantImportResult] */
        ResponseModel_VariantImportResult_: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["VariantImportResult"] | null;
        };
        /** ResponseModel[list[FolderTreeNode]] */
        ResponseModel_list_FolderTreeNode__: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Data */
            data?: components["schemas"]["FolderTreeNode"][] | null;
        };
        /** ResponseModel[list[ServerCommandSpec]] */
        ResponseModel_list_ServerCommandSpec__: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Data */
            data?: components["schemas"]["ServerCommandSpec"][] | null;
        };
        /** ResponseModel[list[Union[SymbolTreeGroupNode, SymbolTreeSymbolNode]]] */
        ResponseModel_list_Union_SymbolTreeGroupNode__SymbolTreeSymbolNode___: {
            /** Success */
            success: boolean;
            /** Message */
            message?: string | null;
            /** Data */
            data?: (components["schemas"]["SymbolTreeGroupNode"] | components["schemas"]["SymbolTreeSymbolNode"])[] | null;
        };
        /**
         * ScanProgress
         * @description 扫描任务进度。
         */
        ScanProgress: {
            /** Taskid */
            taskId: string;
            state: components["schemas"]["ScanTaskState"];
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Current
             * @default 0
             */
            current: number;
            /**
             * Currentfile
             * @default
             */
            currentFile: string;
            /** Matches */
            matches?: components["schemas"]["ConversionMatch"][] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ScanRequest
         * @description 启动扫描请求。
         */
        ScanRequest: {
            /** Mode */
            mode: string;
            /** Imagepaths */
            imagePaths?: string[] | null;
            /** Screenshotpath */
            screenshotPath?: string | null;
            /** Singleimagepath */
            singleImagePath?: string | null;
        };
        /**
         * ScanStartResponse
         * @description 启动扫描响应。
         */
        ScanStartResponse: {
            /** Taskid */
            taskId: string;
        };
        /**
         * ScanTaskState
         * @description 扫描任务状态枚举。
         * @enum {string}
         */
        ScanTaskState: "pending" | "classifying" | "scanning" | "completed" | "cancelled" | "error";
        /** ServerCommandSpec */
        ServerCommandSpec: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Args Schema */
            args_schema: {
                [key: string]: string;
            };
        };
        /**
         * SuggestPathResponse
         * @description AI 路径建议响应。
         *
         *     直接透传 AI 服务返回的目录与文件名建议。
         */
        SuggestPathResponse: {
            /** Suggesteddir */
            suggestedDir: string;
            /** Suggestedfilename */
            suggestedFilename: string;
            /** Reason */
            reason: string;
        };
        /**
         * SymbolIndexHealthModel
         * @description 符号索引健康状态。
         */
        SymbolIndexHealthModel: {
            /** Ready */
            ready: boolean;
            /** Indexversion */
            indexVersion: number;
            /** Lastbuildms */
            lastBuildMs: number;
            /** Filecount */
            fileCount: number;
            /** Symbolcount */
            symbolCount: number;
        };
        /**
         * SymbolLiteModel
         * @description 符号轻量模型。
         */
        SymbolLiteModel: {
            /** Symbolkey */
            symbolKey: string;
            /** Definitionid */
            definitionId: string;
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Displayname */
            displayName: string | null;
            /** Description */
            description: string | null;
            /** Prefabid */
            prefabId: string | null;
            /** Variant */
            variant: string | null;
            /** Metapath */
            metaPath: string;
            /** Imagepath */
            imagePath: string;
            /** Primarygeometry */
            primaryGeometry: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SymbolSnapshotLiteModel
         * @description 符号索引轻量快照。
         */
        SymbolSnapshotLiteModel: {
            /** Indexversion */
            indexVersion: number;
            /** Contenthash */
            contentHash: string;
            /** Symbols */
            symbols: components["schemas"]["SymbolLiteModel"][];
            stats: components["schemas"]["SymbolSnapshotStatsModel"];
        };
        /**
         * SymbolSnapshotStatsModel
         * @description 符号快照统计。
         */
        SymbolSnapshotStatsModel: {
            /** Filecount */
            fileCount: number;
            /** Symbolcount */
            symbolCount: number;
            /** Diagnosticcount */
            diagnosticCount: number;
        };
        /** SymbolTreeFileNode */
        SymbolTreeFileNode: {
            /**
             * Kind
             * @constant
             */
            kind: "file";
            /** Label */
            label: string;
            /** Metapath */
            metaPath: string;
            /** Imagepath */
            imagePath: string;
            /** Definitionid */
            definitionId: string;
            /** Variant */
            variant?: string | null;
        };
        /** SymbolTreeGroupNode */
        SymbolTreeGroupNode: {
            /**
             * Kind
             * @constant
             */
            kind: "group";
            /** Label */
            label: string;
            /** Children */
            children: (components["schemas"]["SymbolTreeGroupNode"] | components["schemas"]["SymbolTreeSymbolNode"])[];
        };
        /** SymbolTreeSymbolNode */
        SymbolTreeSymbolNode: {
            /**
             * Kind
             * @constant
             */
            kind: "symbol";
            /** Label */
            label: string;
            /** Fullname */
            fullName: string;
            /** Displayname */
            displayName?: string | null;
            /** Children */
            children: components["schemas"]["SymbolTreeVariantNode"][];
        };
        /** SymbolTreeVariantNode */
        SymbolTreeVariantNode: {
            /**
             * Kind
             * @constant
             */
            kind: "variant";
            /** Label */
            label: string;
            /** Children */
            children: components["schemas"]["SymbolTreeFileNode"][];
        };
        /**
         * SymbolUpdateResultModel
         * @description 符号索引增量更新结果。
         */
        SymbolUpdateResultModel: {
            /** Indexversion */
            indexVersion: number;
            /** Contenthash */
            contentHash: string;
            /** Updatedmetapath */
            updatedMetaPath: string;
            /** Removedsymbolkeys */
            removedSymbolKeys: string[];
            /** Upsertedsymbols */
            upsertedSymbols: components["schemas"]["SymbolLiteModel"][];
            /** Diagnostics */
            diagnostics: components["schemas"]["DiagnosticPayloadModel"][];
        };
        /** UpdateIndexRequest */
        UpdateIndexRequest: {
            /** Metapath */
            metaPath: string;
        };
        /**
         * UploadResult
         * @description 上传结果。
         */
        UploadResult: {
            /** Status */
            status: string;
            /** Target Path */
            target_path: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VariantCloneResult
         * @description 变体克隆结果。
         */
        VariantCloneResult: {
            /** Targetmetapath */
            targetMetaPath: string;
            /** Definitioncount */
            definitionCount: number;
        };
        /** VariantCloneToImageResult */
        VariantCloneToImageResult: {
            /** Targetmetapath */
            targetMetaPath: string;
            /** Definitioncount */
            definitionCount: number;
        };
        /** VariantCopySelectedPrefabPrecheckResult */
        VariantCopySelectedPrefabPrecheckResult: {
            /** Targetimagepath */
            targetImagePath: string;
            /** Targetimageexists */
            targetImageExists: boolean;
            /** Targetmetapath */
            targetMetaPath: string;
            /** Targetmetaexists */
            targetMetaExists: boolean;
            /** Targetdefinitionexists */
            targetDefinitionExists: boolean;
            /** Sourcedefinitionid */
            sourceDefinitionId: string;
            /** Sourcedefinitionname */
            sourceDefinitionName: string;
            /** Targetdefinition */
            targetDefinition: {
                [key: string]: unknown;
            };
        };
        /** VariantData */
        VariantData: {
            /** Variants */
            variants?: string[] | null;
            /** Base */
            base?: string | null;
            /** Path Pattern */
            path_pattern?: string | null;
        };
        /** VariantImportImageResult */
        VariantImportImageResult: {
            /** Targetimagepath */
            targetImagePath: string;
            /** Size */
            size: number;
        };
        /**
         * VariantImportPrecheckResult
         * @description 变体导入预检结果。
         */
        VariantImportPrecheckResult: {
            /** Targetimagepath */
            targetImagePath: string;
            /** Targetimageexists */
            targetImageExists: boolean;
            /** Targetmetapath */
            targetMetaPath: string;
            /** Targetmetaexists */
            targetMetaExists: boolean;
            /** Copieddefinitions */
            copiedDefinitions: {
                [key: string]: string;
            }[];
            /** Skippeddefinitions */
            skippedDefinitions: {
                [key: string]: string;
            }[];
        };
        /**
         * VariantImportResult
         * @description 变体导入结果。
         */
        VariantImportResult: {
            /** Targetimagepath */
            targetImagePath: string;
            /** Size */
            size: number;
        };
        /** WriteTextRequest */
        WriteTextRequest: {
            /** Content */
            content: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_dir_api_fs_list_dir_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ListDirResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_text_api_fs_read_text_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ReadTextResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_text_api_fs_write_text_put: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_path_api_fs_rename_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenamePathRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_RenameResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copy_file_api_fs_copy_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyFileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_CopyResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_fs_upload_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_fs_upload_file_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_UploadResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_in_explorer_api_fs_reveal_in_explorer_post: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_folder_tree_api_fs_folder_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_list_FolderTreeNode__"];
                };
            };
        };
    };
    get_project_root_api_project_root_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ProjectRootData_"];
                };
            };
        };
    };
    list_workspace_images_api_project_list_images_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ListImagesResponse_"];
                };
            };
        };
    };
    get_project_symbol_tree_api_project_symbol_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_list_Union_SymbolTreeGroupNode__SymbolTreeSymbolNode___"];
                };
            };
        };
    };
    get_image_api_image_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_thumbnail_api_image_thumbnail_get: {
        parameters: {
            query: {
                path: string;
                size?: number;
                x1?: number | null;
                y1?: number | null;
                x2?: number | null;
                y2?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_hover_preview_api_image_hover_preview_get: {
        parameters: {
            query: {
                path: string;
                size?: number | null;
                x1?: number | null;
                y1?: number | null;
                x2?: number | null;
                y2?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prefabs_schema_api_prefabs_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_PrefabsSchema_"];
                };
            };
        };
    };
    get_meta_index_api_meta_index_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_SymbolSnapshotLiteModel_"];
                };
            };
        };
    };
    update_meta_index_api_meta_index_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIndexRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_SymbolUpdateResultModel_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meta_diagnostics_api_meta_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_MetaDiagnosticsSnapshotModel_"];
                };
            };
        };
    };
    get_meta_index_health_api_meta_index_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_SymbolIndexHealthModel_"];
                };
            };
        };
    };
    clone_variant_to_image_api_meta_variant_clone_to_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloneVariantToImageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_VariantCloneResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    precheck_variant_import_path_api_meta_variant_import_precheck_path_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_precheck_variant_import_path_api_meta_variant_import_precheck_path_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_VariantImportPrecheckResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_variant_image_api_meta_variant_import_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_variant_image_api_meta_variant_import_image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_VariantImportResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    precheck_copy_selected_prefab_to_variant_api_meta_variant_copy_selected_prefab_precheck_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrecheckCopySelectedPrefabToVariantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_CopyPrefabPrecheckResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copy_selected_prefab_to_variant_api_meta_variant_copy_selected_prefab_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopySelectedPrefabToVariantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_CopyPrefabResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    precheck_rename_document_api_fs_rename_document_precheck_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrecheckRenameDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_RenameDocumentPrecheckResultModel_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_rename_document_api_fs_rename_document_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteRenameDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_RenameDocumentExecuteResultModel_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_api_document_create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_document_api_document_create_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_CreateDocumentResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_document_path_api_ai_suggest_path_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_suggest_document_path_api_ai_suggest_path_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_SuggestPathResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    infer_definitions_api_ai_infer_definitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_infer_definitions_api_ai_infer_definitions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_InferDefinitionsResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_adb_devices_api_device_adb_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_DeviceListResult_"];
                };
            };
        };
    };
    capture_adb_screenshot_api_device_adb_screenshot_get: {
        parameters: {
            query: {
                serial: string;
                displayId?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_CaptureScreenshotResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversion_execute_api_conversion_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteConversionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ConversionExecuteResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversion_scan_api_conversion_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ScanStartResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversion_scan_progress_api_conversion_scan_progress__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ScanProgress_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversion_cancel_scan_api_conversion_scan__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_server_commands_api_server_commands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_list_ServerCommandSpec__"];
                };
            };
        };
    };
    execute_server_command_api_server_execute_command_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_Union_MetaRefetchResult__SymbolUpdateResultModel__RenameDocumentPrecheckResultModel__RenameDocumentExecuteResultModel__RenameSymbolPrecheckResult__RenameSymbolExecuteResult__VariantCloneToImageResult__VariantImportImageResult__VariantCopySelectedPrefabPrecheckResult__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_HealthResult_"];
                };
            };
        };
    };
    spa_catchall___path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                _path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
